package interfaz;

import business.Person;
import java.io.File;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JLabel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JTextField;
import javax.swing.JComboBox;
import javax.swing.DefaultComboBoxModel;
import interfaz.CreateJPanel.Departamento;
import java.awt.event.ItemListener;
import java.awt.event.ItemEvent;

public class CreateJPanel extends javax.swing.JPanel {

	/**
	 * Creates new form ControlJPanel
	 */
	Person person;
	Person personIncrement;
	Pattern patNom = Pattern.compile("^[A-Za-z]{1,50}$");
	Pattern patTelf = Pattern.compile("^[67]\\d{8}$");
	Pattern patEmail = Pattern.compile("^\\w+@\\w+\\.[a-z]{2,3}$");
	Pattern patBanco = Pattern.compile("^ES\\d{2}-\\d{4}-\\d{4}-\\d{2}-\\d{10}$");
	Pattern patSS = Pattern.compile("^\\d{10}$");
	String departamento = "Marketing";

	enum Departamento {
		MARKETING, TIC, ADMINISTRATIVO
	};

	public CreateJPanel(Person person) {
		initComponents();
		this.person = person;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
// <editor-fold defaultstate="collapsed" desc="Generated
// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		picTextPath = new javax.swing.JTextField();
		createBtn = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		nameTextField = new javax.swing.JTextField();
		geoTextField = new javax.swing.JTextField();
		dobTextField = new javax.swing.JTextField();
		phoneTextField = new javax.swing.JTextField();
		ssnTextField = new javax.swing.JTextField();
		emailTextField = new javax.swing.JTextField();
		bankTextField = new javax.swing.JTextField();

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
		jLabel1.setText("Create Profile");

		jButton1.setText("Select Photo");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		picTextPath.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				picTextPathActionPerformed(evt);
			}
		});

		createBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // departamentoNOI18N
		createBtn.setText("Create");
		createBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				createBtnActionPerformed(evt);
			}
		});

		jLabel2.setText("Name: ");

		jLabel3.setText("Geographic Data: ");

		jLabel4.setText("Date of Birth: ");

		jLabel5.setText("Phone: ");

		jLabel7.setText("Email: ");

		jLabel8.setText("Social Security Number: ");

		jLabel9.setText("Bank Account Number: ");

		emailTextField.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				emailTextFieldActionPerformed(evt);
			}
		});

		lblDepartamento = new JLabel("Departamento:");

		JComboBox comboBox = new JComboBox();
		comboBox.addItemListener(new ItemListener() {
			public void itemStateChanged(ItemEvent arg0) {
				if (comboBox.getSelectedIndex() == 0) {
					departamento = "Marketing";
				} else if (comboBox.getSelectedIndex() == 1) {
					departamento = "TIC";
				} else {
					departamento = "Administrativo";
				}
			}
		});
		comboBox.setModel(new DefaultComboBoxModel(Departamento.values()));

		JLabel lblFechaIncorporacin = new JLabel("Fecha incorporación:");

		textFieldin1 = new JTextField();
		textFieldin1.setColumns(10);

		textFieldin2 = new JTextField();
		textFieldin2.setColumns(10);

		textFieldin3 = new JTextField();
		textFieldin3.setColumns(10);

		textFieldDob1 = new JTextField();

		textFieldDob2 = new JTextField();
		
		sueldoTextField = new JTextField();
		sueldoTextField.setColumns(10);
		
		JLabel lblSueldo = new JLabel("Sueldo:");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addGap(372)
					.addComponent(jLabel1)
					.addGap(0, 191, Short.MAX_VALUE))
				.addGroup(layout.createSequentialGroup()
					.addGap(371)
					.addComponent(createBtn)
					.addContainerGap(283, Short.MAX_VALUE))
				.addGroup(layout.createSequentialGroup()
					.addGap(59)
					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
						.addGroup(layout.createSequentialGroup()
							.addComponent(jLabel3)
							.addPreferredGap(ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
							.addComponent(geoTextField, GroupLayout.PREFERRED_SIZE, 244, GroupLayout.PREFERRED_SIZE))
						.addGroup(layout.createSequentialGroup()
							.addComponent(jLabel2)
							.addPreferredGap(ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
							.addComponent(nameTextField, GroupLayout.PREFERRED_SIZE, 244, GroupLayout.PREFERRED_SIZE))
						.addGroup(layout.createSequentialGroup()
							.addGroup(layout.createParallelGroup(Alignment.LEADING)
								.addComponent(jLabel5)
								.addComponent(jLabel7)
								.addComponent(jLabel8)
								.addComponent(jLabel9)
								.addComponent(lblDepartamento)
								.addComponent(jLabel4)
								.addComponent(lblFechaIncorporacin)
								.addComponent(lblSueldo))
							.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
							.addGroup(layout.createParallelGroup(Alignment.LEADING)
								.addComponent(sueldoTextField, GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
								.addGroup(Alignment.TRAILING, layout.createParallelGroup(Alignment.LEADING, false)
									.addComponent(comboBox, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
									.addComponent(phoneTextField, GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
									.addComponent(ssnTextField)
									.addComponent(emailTextField, GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
									.addComponent(bankTextField)
									.addGroup(layout.createSequentialGroup()
										.addComponent(dobTextField, GroupLayout.PREFERRED_SIZE, 82, GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(ComponentPlacement.RELATED)
										.addComponent(textFieldDob1, GroupLayout.PREFERRED_SIZE, 76, GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(ComponentPlacement.RELATED)
										.addComponent(textFieldDob2, GroupLayout.PREFERRED_SIZE, 76, GroupLayout.PREFERRED_SIZE))
									.addGroup(layout.createSequentialGroup()
										.addComponent(textFieldin1, GroupLayout.PREFERRED_SIZE, 77, GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(ComponentPlacement.RELATED)
										.addComponent(textFieldin2, GroupLayout.PREFERRED_SIZE, 77, GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(ComponentPlacement.RELATED)
										.addComponent(textFieldin3, GroupLayout.PREFERRED_SIZE, 77, GroupLayout.PREFERRED_SIZE))))))
					.addGap(12)
					.addComponent(picTextPath, GroupLayout.PREFERRED_SIZE, 149, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(ComponentPlacement.UNRELATED)
					.addComponent(jButton1)
					.addGap(39))
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addGap(47)
					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
						.addGroup(layout.createSequentialGroup()
							.addComponent(jLabel1)
							.addGap(27)
							.addComponent(jLabel2)
							.addPreferredGap(ComponentPlacement.UNRELATED)
							.addComponent(jLabel3))
						.addGroup(layout.createSequentialGroup()
							.addGroup(layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(nameTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(picTextPath, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(jButton1))
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(geoTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(layout.createParallelGroup(Alignment.LEADING)
						.addGroup(layout.createParallelGroup(Alignment.BASELINE)
							.addComponent(dobTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
							.addComponent(jLabel4))
						.addGroup(layout.createParallelGroup(Alignment.BASELINE)
							.addComponent(textFieldDob1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
							.addComponent(textFieldDob2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(phoneTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel5))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(emailTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel7))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(ssnTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel8))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(bankTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel9))
					.addGroup(layout.createParallelGroup(Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
							.addGap(10)
							.addComponent(lblDepartamento)
							.addPreferredGap(ComponentPlacement.UNRELATED)
							.addComponent(lblFechaIncorporacin)
							.addPreferredGap(ComponentPlacement.UNRELATED)
							.addComponent(lblSueldo))
						.addGroup(layout.createSequentialGroup()
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(comboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
							.addPreferredGap(ComponentPlacement.RELATED)
							.addGroup(layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(textFieldin1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(textFieldin2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(textFieldin3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(sueldoTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
					.addGap(32)
					.addComponent(createBtn)
					.addContainerGap(63, Short.MAX_VALUE))
		);
		this.setLayout(layout);
	}// </editor-fold>//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
		JFileChooser chooser = new JFileChooser();
		chooser.showOpenDialog(null);
		File f = chooser.getSelectedFile();
		String fileName = f.getAbsolutePath();
		picTextPath.setText(fileName);

	}// GEN-LAST:event_jButton1ActionPerformed

	private void picTextPathActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_picTextPathActionPerformed
// TODO add your handling code here:
	}// GEN-LAST:event_picTextPathActionPerformed

	private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_createBtnActionPerformed
// TODO add your handling code here:

		Matcher matNom = patNom.matcher(nameTextField.getText());
		Matcher matNomPais = patNom.matcher(geoTextField.getText());
		Matcher matTelf = patTelf.matcher(phoneTextField.getText());
		Matcher matEmail = patEmail.matcher(emailTextField.getText());
		Matcher matBanco = patBanco.matcher(bankTextField.getText());
		Matcher matSS = patSS.matcher(ssnTextField.getText());

		if (!matNom.matches()) {
			JOptionPane.showMessageDialog(null, "El nombre es incorrecto");
		} else if (!matNomPais.matches()) {
			JOptionPane.showMessageDialog(null, "El pais es incorrecto");
		} else if (!matTelf.matches()) {
			JOptionPane.showMessageDialog(null, "El número de teléfono es incorrecto");
		} else if (!matEmail.matches()) {
			JOptionPane.showMessageDialog(null, "El correo es incorrecto");
		} else if (!matBanco.matches()) {
			JOptionPane.showMessageDialog(null, "La cuenta es incorrecta");
		} else if (!matSS.matches()) {
			JOptionPane.showMessageDialog(null, "El número de la SS es incorrecto");
		} else {

			try {
				LocalDate fechaNac = LocalDate
						.parse(textFieldDob2.getText() + "-" + textFieldDob1.getText() + "-" + dobTextField.getText());
				LocalDate fechaIn = LocalDate
						.parse(textFieldin3.getText() + "-" + textFieldin2.getText() + "-" + textFieldin1.getText());

				if (!(fechaNac.getYear() >= 18)) {
					JOptionPane.showMessageDialog(null, "Debe ser mayor de edad");
				} else {
					DateTimeFormatter fechaFormateada = DateTimeFormatter.ofPattern("dd-MM-yyyy");

					
					personIncrement = new Person();
					
					String imagen = picTextPath.getText();
					String nombre = nameTextField.getText();
					String pais = geoTextField.getText();
					String nac = fechaNac.format(fechaFormateada).toString();
					String tlf = phoneTextField.getText();
					String email = emailTextField.getText();
					String nSS = ssnTextField.getText();
					String banco = bankTextField.getText();
					String dpto =  departamento.toString();
					String inc = fechaIn.format(fechaFormateada).toString();
					String sueldo = sueldoTextField.getText();

					JOptionPane.showMessageDialog(null, "Profile created successfully !!!");

				}

			} catch (DateTimeParseException e) {
				JOptionPane.showMessageDialog(null, "La fecha es incorrecta");
			} catch (IllegalArgumentException e) {
				JOptionPane.showMessageDialog(null, "La fecha es incorrecta2");
			}
//catch (IllegalArgumentException e) {

//}
		}

	}// GEN-LAST:event_createBtnActionPerformed

	private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_emailTextFieldActionPerformed
// TODO add your handling code here:
	}// GEN-LAST:event_emailTextFieldActionPerformed

// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JTextField bankTextField;
	private javax.swing.JButton createBtn;
	private javax.swing.JTextField dobTextField;
	private javax.swing.JTextField emailTextField;
	private javax.swing.JTextField geoTextField;
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JTextField nameTextField;
	private javax.swing.JTextField phoneTextField;
	private javax.swing.JTextField picTextPath;
	private javax.swing.JTextField ssnTextField;
	private javax.swing.JComboBox comboBox;
	private JLabel lblDepartamento;
	private JTextField textFieldin1;
	private JTextField textFieldin2;
	private JTextField textFieldin3;
	private JTextField textFieldDob1;
	private JTextField textFieldDob2;
	private JTextField sueldoTextField;
	private javax.swing.JLabel lblSueldo;
}