package interfaz;

import business.Person;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.List;

import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JTextField;

public class DisplayJPanel extends javax.swing.JPanel {

	/**
	 * Creates new form DisplayJPanel
	 */
// Person person;
	public DisplayJPanel(List<Person> empleados, int incArray) {
		initComponents();
// this.person=person;
		displayPerson(empleados, incArray);
	}

	public void displayPerson(List<Person> empleados, int incArray) {

		try {

			nameTextField.setText(((Person) empleados.get(incArray)).getName());
			emailTextField.setText(((Person) empleados.get(incArray)).getEmail());
			ssnTextField.setText(((Person) empleados.get(incArray)).getSsn());
			dobTextField.setText(((Person) empleados.get(incArray)).getDob());
			geoTextField.setText(((Person) empleados.get(incArray)).getGeographic_data());
			bankTextField.setText(((Person) empleados.get(incArray)).getBankAccNum());
			phoneTextField.setText(((Person) empleados.get(incArray)).getPhone());
			jLabel12_1.setText(String.valueOf(((Person) empleados.get(incArray)).getEmpcode()));
			lblDepartamento_1.setText(((Person) empleados.get(incArray)).getDepartamento());
			textFieldin.setText(((Person) empleados.get(incArray)).getIncorporacion());
			sueldoTextField.setText(String.valueOf(((Person) empleados.get(incArray)).getSueldo()));

			String imageTxt = ((Person) empleados.get(incArray)).getImagetxt();
			// imagePatTxt.setText(imageTxt);

			try {
				BufferedImage img = ImageIO.read(new File(imageTxt));

				imageLabel.setBounds(100, 100, 280, 250);

				Image dimg = img.getScaledInstance(imageLabel.getWidth(), imageLabel.getHeight(), Image.SCALE_SMOOTH);
				ImageIcon icon = new ImageIcon(dimg);

				imageLabel.setIcon(icon);
			} catch (IOException e) {
				e.printStackTrace();
			}
		} catch (NullPointerException e) {
			System.out.println("No hay ningun perfil creado");
		}

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")

// <editor-fold defaultstate="collapsed" desc="Generated
// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		imageLabel = new javax.swing.JLabel();
		dobTextField = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		bankTextField = new javax.swing.JTextField();
		ssnTextField = new javax.swing.JTextField();
		emailTextField = new javax.swing.JTextField();
		phoneTextField = new javax.swing.JTextField();
		geoTextField = new javax.swing.JTextField();
		nameTextField = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();

		imageLabel.setBackground(new java.awt.Color(102, 102, 102));
		imageLabel.setOpaque(true);

		dobTextField.setEditable(false);

		jLabel2.setText("Name: ");

		jLabel3.setText("Geographic Data: ");

		jLabel4.setText("Date of Birth: ");

		jLabel5.setText("Phone: ");

		jLabel7.setText("Email: ");

		jLabel8.setText("Social Security Number: ");

		jLabel9.setText("Bank Account Number: ");

		bankTextField.setEditable(false);

		ssnTextField.setEditable(false);

		emailTextField.setEditable(false);
		emailTextField.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				emailTextFieldActionPerformed(evt);
			}
		});

		phoneTextField.setEditable(false);

		geoTextField.setEditable(false);

		nameTextField.setEditable(false);

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
		jLabel1.setText("Display Profile");

		jLabel11_1 = new JLabel("Employees code:");

		jLabel12_1 = new JLabel("");

		lblDepartamento = new JLabel("Departamento:");

		lblDepartamento_1 = new JLabel("");

		lblFechaIncorporacin = new JLabel("Fecha incorporación:");

		textFieldin = new JTextField();
		textFieldin.setText((String) null);
		textFieldin.setEditable(false);
		
		sueldoTextField = new JTextField();
		sueldoTextField.setText((String) null);
		sueldoTextField.setEditable(false);
		
		lblSueldo = new JLabel("Sueldo:");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(layout.createSequentialGroup()
					.addGroup(layout.createParallelGroup(Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
							.addContainerGap(282, Short.MAX_VALUE)
							.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 212, GroupLayout.PREFERRED_SIZE))
						.addGroup(layout.createSequentialGroup()
							.addGap(60)
							.addGroup(layout.createParallelGroup(Alignment.TRAILING)
								.addGroup(layout.createSequentialGroup()
									.addGroup(layout.createParallelGroup(Alignment.LEADING)
										.addGroup(layout.createParallelGroup(Alignment.TRAILING)
											.addGroup(layout.createSequentialGroup()
												.addGroup(layout.createParallelGroup(Alignment.LEADING)
													.addComponent(jLabel7)
													.addComponent(jLabel9)
													.addComponent(lblDepartamento)
													.addComponent(lblFechaIncorporacin))
												.addPreferredGap(ComponentPlacement.RELATED, 27, Short.MAX_VALUE))
											.addGroup(layout.createSequentialGroup()
												.addComponent(jLabel8)
												.addPreferredGap(ComponentPlacement.UNRELATED)))
										.addGroup(layout.createSequentialGroup()
											.addComponent(lblSueldo)
											.addPreferredGap(ComponentPlacement.RELATED)))
									.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
										.addComponent(bankTextField)
										.addComponent(ssnTextField, GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
										.addComponent(emailTextField, GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
										.addComponent(lblDepartamento_1)
										.addComponent(textFieldin, GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
										.addComponent(sueldoTextField, GroupLayout.PREFERRED_SIZE, 244, GroupLayout.PREFERRED_SIZE)))
								.addGroup(layout.createSequentialGroup()
									.addComponent(jLabel3)
									.addPreferredGap(ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
									.addComponent(geoTextField, GroupLayout.PREFERRED_SIZE, 244, GroupLayout.PREFERRED_SIZE))
								.addGroup(layout.createSequentialGroup()
									.addComponent(jLabel5)
									.addPreferredGap(ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
									.addComponent(phoneTextField, GroupLayout.PREFERRED_SIZE, 244, GroupLayout.PREFERRED_SIZE))
								.addGroup(layout.createSequentialGroup()
									.addComponent(jLabel4)
									.addPreferredGap(ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
									.addComponent(dobTextField, GroupLayout.PREFERRED_SIZE, 244, GroupLayout.PREFERRED_SIZE))
								.addGroup(layout.createSequentialGroup()
									.addComponent(jLabel2)
									.addPreferredGap(ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
									.addComponent(nameTextField, GroupLayout.PREFERRED_SIZE, 244, GroupLayout.PREFERRED_SIZE))
								.addComponent(jLabel11_1, GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
								.addComponent(jLabel12_1, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE))))
					.addGap(110)
					.addComponent(imageLabel, GroupLayout.PREFERRED_SIZE, 274, GroupLayout.PREFERRED_SIZE)
					.addGap(260))
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addGap(74)
					.addComponent(jLabel1)
					.addGap(68)
					.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
						.addGroup(layout.createSequentialGroup()
							.addComponent(jLabel11_1)
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(jLabel12_1)
							.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
							.addGroup(layout.createParallelGroup(Alignment.TRAILING)
								.addGroup(layout.createSequentialGroup()
									.addComponent(jLabel2)
									.addGap(27))
								.addGroup(layout.createSequentialGroup()
									.addComponent(nameTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
									.addPreferredGap(ComponentPlacement.RELATED)
									.addGroup(layout.createParallelGroup(Alignment.BASELINE)
										.addComponent(geoTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel3))))
							.addPreferredGap(ComponentPlacement.RELATED)
							.addGroup(layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(dobTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel4))
							.addPreferredGap(ComponentPlacement.RELATED)
							.addGroup(layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(phoneTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel5))
							.addPreferredGap(ComponentPlacement.RELATED)
							.addGroup(layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(emailTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel7))
							.addPreferredGap(ComponentPlacement.RELATED)
							.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
								.addGroup(layout.createSequentialGroup()
									.addComponent(jLabel8)
									.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
									.addGroup(layout.createParallelGroup(Alignment.BASELINE)
										.addComponent(bankTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel9)))
								.addGroup(layout.createSequentialGroup()
									.addComponent(ssnTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
									.addGap(27)))
							.addPreferredGap(ComponentPlacement.RELATED)
							.addGroup(layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(lblDepartamento)
								.addComponent(lblDepartamento_1))
							.addGap(4))
						.addGroup(layout.createSequentialGroup()
							.addComponent(imageLabel, GroupLayout.PREFERRED_SIZE, 238, GroupLayout.PREFERRED_SIZE)
							.addGap(36)))
					.addPreferredGap(ComponentPlacement.UNRELATED)
					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(textFieldin, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(lblFechaIncorporacin))
					.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(sueldoTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(lblSueldo)))
		);
		this.setLayout(layout);
	}// </editor-fold>//GEN-END:initComponents

	private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_emailTextFieldActionPerformed
// TODO add your handling code here:
	}// GEN-LAST:event_emailTextFieldActionPerformed

// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JTextField bankTextField;
	private javax.swing.JTextField dobTextField;
	private javax.swing.JTextField emailTextField;
	private javax.swing.JTextField geoTextField;
	private javax.swing.JLabel imageLabel;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JLabel jLabel11;
	private JLabel jLabel11_1;
	private javax.swing.JLabel jLabel12;
	private JLabel jLabel12_1;
	private javax.swing.JTextField nameTextField;
	private javax.swing.JTextField phoneTextField;
	private javax.swing.JTextField ssnTextField;
	private JLabel lblDepartamento;
	private JLabel lblDepartamento_1;
	private JLabel lblFechaIncorporacin;
	private JTextField textFieldin;
	private JTextField sueldoTextField;
	private JLabel lblSueldo;
}
